# Infer Steiner Nodes By Median

In [17]:
import numpy as np
import statistics as stat

In [37]:
cell_cnt_pattern1 = np.array([2,2,2,2]).astype(int)
cell_cnt_pattern2 = np.array([2,4,1,1]).astype(int)
cell_cnt_pattern3 = np.array([2,0,3,3]).astype(int)
cell_cnt_patterns = np.row_stack([cell_cnt_pattern1, cell_cnt_pattern2, cell_cnt_pattern3])

In [38]:
cell_cnt_patterns

array([[2, 2, 2, 2],
       [2, 4, 1, 1],
       [2, 0, 3, 3]])

In [43]:
median_steiner = np.median(cell_cnt_patterns, axis=0).astype(int)

FLAG = False

for i in range(cell_cnt_patterns.shape[0]):
    if np.array_equal(median_steiner,cell_cnt_patterns[i,:])==True:
        FLAG = True
if FLAG:
    print("There is no extra Steiner Node!")
else:
    print(median_steiner)

There is no extra Steiner Node!


In [44]:
cell_cnt_pattern1 = np.array([2,2,2,2]).astype(int)
cell_cnt_pattern2 = np.array([2,4,1,3]).astype(int)
cell_cnt_pattern3 = np.array([2,3,1,1]).astype(int)
cell_cnt_patterns = np.row_stack([cell_cnt_pattern1, cell_cnt_pattern2, cell_cnt_pattern3])

In [45]:
cell_cnt_patterns

array([[2, 2, 2, 2],
       [2, 4, 1, 3],
       [2, 3, 1, 1]])

In [46]:
median_steiner = np.median(cell_cnt_patterns, axis=0).astype(int)

FLAG = False

for i in range(cell_cnt_patterns.shape[0]):
    if np.array_equal(median_steiner,cell_cnt_patterns[i,:])==True:
        FLAG = True
if FLAG:
    print("There is no extra Steiner Node!")
else:
    print(median_steiner)

[2 3 1 2]
